language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

# XDebug slows down Composer ... our run-tests.sh script will enable it later
before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - sh -c "composer install --no-progress"

script: ./run-tests.sh
